-- ==========================================
-- GLOBAL SEQUENCES FOR ID PARTITIONING
-- ==========================================
-- This file defines centralized sequences for all tables.
-- Each sequence uses a designated 5-digit block for human-readability.

-- 1. Standard Lookup (1+)
CREATE SEQUENCE MAXXBRANDS.seq_role_id        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MAXXBRANDS.seq_employee_id    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MAXXBRANDS.seq_user_id        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MAXXBRANDS.seq_category_id    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MAXXBRANDS.seq_attendance_id  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MAXXBRANDS.seq_log_id         START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MAXXBRANDS.seq_location_id    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MAXXBRANDS.seq_customer_id    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MAXXBRANDS.seq_supplier_id    START WITH 1 INCREMENT BY 1 NOCACHE;

-- 2. Catalog & Inventory (100 - 2000)
CREATE SEQUENCE MAXXBRANDS.seq_type_id        START WITH 500  INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MAXXBRANDS.seq_item_id        START WITH 100  INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MAXXBRANDS.seq_attribute_id   START WITH 200  INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MAXXBRANDS.seq_inventory_id   START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MAXXBRANDS.seq_alert_id       START WITH 2000 INCREMENT BY 1 NOCACHE;

-- 3. Procurement (10,000 block)
CREATE SEQUENCE MAXXBRANDS.seq_po_id          START WITH 10000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MAXXBRANDS.seq_po_line_id     START WITH 11000 INCREMENT BY 1 NOCACHE;

-- 4. Sales (20,000 block)
CREATE SEQUENCE MAXXBRANDS.seq_sale_id        START WITH 20000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MAXXBRANDS.seq_sale_item_id   START WITH 21000 INCREMENT BY 1 NOCACHE;

-- 5. Workflow (30,000 - 50,000)
CREATE SEQUENCE MAXXBRANDS.seq_purchase_id    START WITH 30000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MAXXBRANDS.seq_tracking_id    START WITH 31000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MAXXBRANDS.seq_fulfillment_id START WITH 40000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MAXXBRANDS.seq_payment_id     START WITH 50000 INCREMENT BY 1 NOCACHE;

COMMIT;
